server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth.samples: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.security.oauth2.client: TRACE
    reactor.netty: DEBUG  # See https://github.com/reactor/reactor-netty/issues/233

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          gusto:
            provider: gusto
            client-id: igF4ABTff_pkvy8j8YT39bd1kaWpEq2Vc-Hal6Amlbk
            client-secret: iRlKbMWSaaCUTDjkkct1T-GpAgv3mde4OAT1dLw82Os
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/authorized/'
        provider:
          gusto:
            authorization-uri: https://api.gusto-demo.com/oauth/authorize
            token-uri: https://api.gusto-demo.com/oauth/token
#  profiles:
#    active: 
gusto-api:
  current-user-endpoint: https://api.gusto-demo.com/v1/me
  employees-endpoint: https://api.gusto-demo.com/v1/companies/7756341741017369/employees
