server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          gusto-client:
            provider: gusto-provider
            client-id: igF4ABTff_pkvy8j8YT39bd1kaWpEq2Vc-Hal6Amlbk
            client-secret: iRlKbMWSaaCUTDjkkct1T-GpAgv3mde4OAT1dLw82Os
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized/"
#            redirect-uri: "https://lendwithconfidence.com/login/"
#            scope: message.read,message.write
        provider:
          keycloak:
            authorization-uri: http://auth-server:8090/auth/realms/oauth2-sample/protocol/openid-connect/auth
            token-uri: http://auth-server:8090/auth/realms/oauth2-sample/protocol/openid-connect/token
          gusto-provider:
            authorization-uri: https://api.gusto-demo.com/oauth/authorize
            token-uri: https://api.gusto-demo.com/oauth/token
#  profiles:
#    active: 
gusto-api:
  base-uri: https://api.gusto-demo.com/v1/me
